baseURL = 'https://tsingwang.github.io/'
googleAnalytics = 'G-S6RJ272SMM'
languageCode = 'zh-cn'
title = 'A little thoughts by Tsing'
theme = 'flat'
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 10

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true

[[menus.main]]
name = "Wiki"
url = "https://tsingwang.github.io/wiki/"
weight = 30

#[[menus.main]]
#pageref = "about"
#name = "About"
#weight = 80
